### PR TITLE
Adds layer info button to map view

### PR DESCRIPTION
**Pull request by ahmdthr**
Added an info button to the table of content to view details of layer when viewing maps.

Resolves https://github.com/Thuenen-GeoNode-Development/Sprints/issues/10

### CODE REVIEW

**Comment by ridoo** [comment]
Refers to https://github.com/Thuenen-GeoNode-Development/Sprints/issues/10

**Comment by ridoo** [comment]
@ahmdthr I did a quick test on the feature and it looks good. The button appears on the toolbar on an existing map.

One thing I noticed: When creating a map the info button does not show up:

image

**Review by ridoo — CHANGES_REQUESTED** [review]
@ahmdthr Is there a reason why you did not just use the 

https://github.com/Thuenen-GeoNode-Development/geonode-mapstore-client/blob/57c22baeec270d8360c2c5c6297de451e11193b2/geonode_mapstore_client/static/mapstore/configs/localConfig.json#L922

configuration? It seems, that your `LayerDetailViewer` is a copy of `DetailViewer` but I may overlook something here.

**Comment by ahmdthr** [comment]
> @ahmdthr Is there a reason why you did not just use the
> 
> https://github.com/Thuenen-GeoNode-Development/geonode-mapstore-client/blob/57c22baeec270d8360c2c5c6297de451e11193b2/geonode_mapstore_client/static/mapstore/configs/localConfig.json#L922
> 
> configuration? It seems, that your `LayerDetailViewer` is a copy of `DetailViewer` but I may overlook something here.

The reason for introducing `LayerDetailViewer` instead of reusing `DetailViewer` is that there is only one resource state which is already filled in with the currently selected map's details and action bar buttons are linked to that map resource. `LayerDetailViewer` reads from new state `layerDataset`.

**Review by ridoo — COMMENTED** [review]
all good

**Pull request merged**
